### ISSUE TITLE
[Suggestion] Alternative way to initialize the RDF store

### ISSUE THREAD

**Issue by H-Kwon** [4TUResearchData/djehuty#10]
Currently, ORCID doesn't allow redirect URIs using HTTP. Therefore, I am using `uwsgi` command to run Djehuty over HTTPS. However, when running Djehuty for the first time, there is no way to initialize the RDF store with uwsgi.

Therefore, I had to run these commands in a row separately.

> \# Make sure there is no .djehuty-initialized file
> $ rm .djehuty-initialized
> 
> \# Initialize the RDF store using djehuty command
> $ djehuty web -r -d -i -c config.xml
>
> \# Once the admin account has been created, kill the djehuty process
> $ kill -9 <DJEHUTY_WEB_PROCESS_ID>
> 
> \# Run uwsgi to serve the Djehuty web service over HTTPS
> $ uwsgi --https-socket 0.0.0.0:8080,example.crt,example.key --need-plugin python3,http --wsgi-file src/djehuty/web/ui.py --env DJEHUTY_CONFIG_FILE=config.xml --master --processes 4 --threads 4 --stats 0.0.0.0:8081

~I would like to suggest a new option "rdf-store.initialize" having 0 or 1 value so that I can skip the `djehuty web` command.~ I had a look at the code of main function in ui.py initializing the RDF store, and I concluded that adding the initialize option into the XML configuration file doesn't make any sense because:

1. Initialization is something happened only one time in service lifecycle.
2. Every process spawned by uwsgi should check .djehuty-initialized on every request. This just increases disk I/O.

Thus, I would like to suggest a new option in `djehuty` command.

It might seem like this:
```
$ djehuty -h
This is djehuty.

Available subcommands and options:
backup:
...
web:
...
db:
   --initialize      -i Populate the RDF store with default triples
   --conntest        -t Test connection to the SPARQL endpoint
                        and validate the essential datasets.

$ djehuty db -i
Initializing... Done

$ djehuty db -t
Connecting to http://localhost:8082/sparql...
Verify SELECT... OK
Verify UPDATE... OK
...
```

**Comment by roelj** [comment]
Hi @H-Kwon. Thank you for looking into running an instance of Djehuty and suggesting improvements.

Just a small note:
> Currently, ORCID doesn't allow redirect URIs using HTTP. 

There's an exception for `localhost` connections.  So for your development setup you can either roll out a certificate, or use HTTP on `localhost`.

As for the alternative subcommand to initialize the web service: Ideally, we would not need to initialize it at all.  There are two reasons we need to initialize currently:
1. Pre-defined data like licences and categories;
2. Coupling an e-mail address to ORCID.  Djehuty doesn't create accounts for the ORCID authentication method, so they must be defined/established beforehand.

The restriction of (2) can be resolved by implementing account creation from the information provided by ORCID.
I don't know how we could solve (1) other than having a check in place similar to what `--initialize` does.

Nevertheless, I like the idea of changing how initialization works right now. I would like to propose to keep it under the `web` subcommand:
```
$ djehuty web --initialize ...
Initializing... Done.
$ djehuty web --initialize ...
Initializing... Skipped.
```

So, the `--initialize` option in the `web` subcommand exits after initialization. We could have a check that looks in the database for licences and/or categories to determine whether it's already initialized and skip if that is the case, so that subsequent calls will not duplicate the categories and licences.

And for testing:
```
$ djehuty web --test-sparql-endpoint
Verify reading from SPARQL endpoint: OK
Verify writing to SPARQL endpoint: OK
```

What do you think?

Thank you again for your efforts. :)

**Comment by roelj** [comment]
Regarding:
> Coupling an e-mail address to ORCID. Djehuty doesn't create accounts for the ORCID authentication method, so they must be defined/established beforehand.

We've implemented "automatic login" as an alternative, so an external Identity Provider is no longer required (for development environments).

The overhead for the `.djehuty-initialized` file is only there when `--initialize` is passed along, which can be easily avoided by not passing it in to the default start command.

Considering this, I'm closing the issue.

Thanks again for your great work the last months on improving Djehuty. :-)
