### ISSUE TITLE
Question about API access and metaprefix

### ISSUE THREAD

**Issue by sefeoglu** [4TUResearchData/djehuty#21]
Hello, 
I would like to harvest the metadata of the datasets from your portal.
Do you have an API like this:  `https://api-depositonce.tu-berlin.de/server/oai/request?verb=ListRecords&metadataPrefix=oai_dc
` ?

Thanks, 
Best,

**Comment by roelj** [comment]
Hi @sefeoglu,

Thank you for your question.
I'm not sure exactly which metadata you're interested in. You can either use our API:
```
https://data.4tu.nl/v2/articles?limit=10000
https://data.4tu.nl/v2/collections?limit=1000
```

Or use the [OAI-PMH interface of DataCite](https://support.datacite.org/docs/datacite-oai-pmh) (because we publish all our metadata to/with DataCite)

I'm very much interested in how the harvesting goes and if there's more we can do to ease the process.
